### ISSUE TITLE
Bad result for VLP-16 input

### ISSUE THREAD

**Issue by poornimajd** [anirudhtopiwala/OpenSource_Problems#1]
Hey @anirudhtopiwala ,great work!
I am trying to convert my vlp-16 point cloud to 2d image by using this repo.I changed the following parameters in the code 
    For VLP-16
    Fov_Up = 15 degrees
    Fov_Down = -15 degrees
    Num of Lasers = 16
    Length of the image =1024
But I got a very bad result.Is there any other thing I am missing out? 

![bad_range](https://user-images.githubusercontent.com/31023599/81102513-5f191100-8f2d-11ea-8158-c6a3a8e8c62f.png)
Thank you

**Comment by anirudhtopiwala** [comment]
Hi, I was not able to replicate a similar image. I have attached the output I get with the parameters you have mentioned. It will be difficult to visualize the image though, as it has only 16 rows or 16 pixels in length. Are you loading test.pcd file in assets?
![Intensity Image_screenshot_05 05 2020](https://user-images.githubusercontent.com/10342930/81123476-282d0600-8f01-11ea-95d1-6fbb3cdf6538.png)

**Comment by poornimajd** [comment]
Thankyou for the response.
The image which is shown by you,is it from a vlp-16 pcd file?
Yes I am loading it in pcd format.I have actually converted a .npy file to a .pcd format.
This is the npy ,the corresponding pcd format file and the image.
https://github.com/poornimajd/show/tree/master
These are the samples from the IDD dataset.

**Comment by anirudhtopiwala** [comment]
So I took a look at the pcd file you provided. There are a couple of things to take into account. 
1) The point cloud you provided is not 360 degrees. Here, the yaw values ranges from -90 to 90 degrees for the provided point cloud. Therefore to shift the origin to the left side as I have mentioned in the [blog](https://medium.com/@topiwala.anirudh/spherical-projection-for-point-clouds-56a2fc258e6c), you need add `pi` to the values you get.  Therefore then the yaw values will range from [0, pi], which can be normalized by dividing by `pi` or the length of the range. 
tl:dr
Change line 74 of [Spherical_View_Projection.cpp](https://github.com/anirudhtopiwala/OpenSource_Problems/blob/master/Spherical_View_Projection/src/Spherical_View_Projection.cpp) to:
`double v = (yaw+ M_PI/2) / M_PI ;`

2) The intensity value in the provided point cloud ranges from [0, 255]. You to need to normalized it by dividing intensity by 255, as the values are in float, opencv expects values between range [0,1]. 
Note: after normalizing it will be difficult to visually understand whats happening in the image, so just for visualizing you can skip this step. Although, if training a deep learning network don't forget to normalize. 

The final output looks like this
![Intensity Image_screenshot_06 05 2020](https://user-images.githubusercontent.com/10342930/81240402-52e88e80-8fd5-11ea-8760-c7a03ce7896d.png)

**Comment by poornimajd** [comment]
Thanks alot for the detailed answer!
